Refactor fbscraper.py to remove facepy dependency
metakgp/naarad-news pull request #73
Opened 2017-02-04 22:30 UTC by ghostwriternr

facepy's fork that has been in active use in naarad has not been updated
in a while, and falls way behind vanilla Graph API in terms of
functionality as well as documentation. Directly interfacing with the
Graph API makes it easier to work with the API, and helps keeping the
code simple enough for future contributors by not adding another
abstraction layer in the middle.

Notes:

  - Regenerated requirements.txt using 'pipreqs' (Please do check if the
  list is exhaustive)
  - [WIP] Cleaned up code to be more in sync with PEP 8 style guide

2017-02-05 06:51 UTC, athityakumar commented
Great. LGTM. :+1: 

@DefCon-007 - There are warnings like Insecure Platform Warning and SNI Missing Warning.
Did these warnings appear before too?

![image](https://cloud.githubusercontent.com/assets/17109060/22624289/26ccd246-eb9d-11e6-81cb-005cf3188456.png)

2017-02-05 06:51 UTC, athityakumar approved these changes

2017-02-05 07:02 UTC, athityakumar requested changes
@ghostwriternr - Just came across this error :

![image](https://cloud.githubusercontent.com/assets/17109060/22624336/26444f5a-eb9f-11e6-8433-2f4dc5ec84ea.png)

2017-02-05 07:36 UTC, DefCon-007 commented
@athityakumar No, These warnings were not there before. And I think they are because of requests module and not due to facebook.

2017-02-05 07:57 UTC, ghostwriternr commented
@athityakumar I will look into the reason for those warnings. Funnily enough, I didn't encounter this when I was testing the code. I'll look into it. Could this be because of difference in Python (and pip package) versions?

Also, I'm not able to replicate the error you have pointed out in the screenshot. [The line](https://github.com/metakgp/naarad-source/pull/73/commits/52933b9f593523881a9f208865442a747d9f4a94#diff-af487accbbb3066ad384c02edccbe788R158) in question is the exception handler for file opening, and I have not edited any of the code in the function call stack till that point. Can you please tell me when does this occur? I might have missed a test case.

2017-02-05 08:34 UTC, athityakumar commented
@ghostwriternr - I'm using python 2.7, and both - the warning & error were due to different python versions.

No FileNotFoundError for Python 2.7 : http://stackoverflow.com/questions/26745283/how-do-i-import-filenotfounderror-from-python-3 
We have to setup `OSError` instead of `FileNotFoundError` for making it work across different Python versions, or simply just have it as `exception:` in that line 158.

The `requests[security]` didn't solve the warnings. Let me check if anything else solves the warning.
Source for future reference : http://stackoverflow.com/questions/19559247/requirements-txt-depending-on-python-version

2017-02-05 08:42 UTC, athityakumar commented
@icyflame @DefCon-007 : Python `2.x` and `3.x` are quite incompatible. Do we need naarad to be supported by both? Anyways, the server has `3.x` currently.

2017-02-05 08:48 UTC, athityakumar approved these changes

2017-02-05 09:26 UTC, DefCon-007 commented
@athityakumar : It will be better if naarad can become cross compatible with python 2 and python 3. How about we create a new issue for it ?

2017-02-05 09:27 UTC, athityakumar commented
@DefCon-007 : Sure.

2017-02-05 09:31 UTC, athityakumar commented
Opened issue #74 . Do test this PR on `3.x` version, @DefCon-007.

2017-02-05 19:04 UTC, ghostwriternr commented
If this is working fine, should I go ahead with fixing the [repeated posts bug](https://github.com/metakgp/naarad-source/issues/49)? 

It should be pretty straightforward now since graph API's [`posts` edge](https://developers.facebook.com/docs/graph-api/reference/v2.8/post) has an `updated_time` field that can be used to easily check for updates to posts in the feed. 

And we could also decide on a rough metric to decide how far back the posts do we traverse to check for edits. Such a simple traversal to, say 10-15 posts, should be enough for our purpose. A comparison based on hash values [using ETags](https://developers.facebook.com/blog/post/627/) might be an overkill (and also ineffective) for our current scraping style.

2017-02-05 19:24 UTC, athityakumar commented
@ghostwriternr - #49 is the thing that's going to matter for a user. So, let's do that first. Range of 10-15 posts seems logical - no sane group would edit a post that is older than that. And we would also need a script that deletes duplicate posts in all existing json files.

2017-02-05 19:30 UTC, ghostwriternr commented
@athityakumar : Noted. Will incorporate both when I'm done with my classes tomorrow.

2017-02-06 14:58 UTC, icyflame commented
> Python 2.x and 3.x are quite incompatible. Do we need naarad to be supported by both? Anyways, the server has 3.x currently.

There's not much sense in making this cross compatible. A better choice would be to use Python 3.

If you are having to add dependencies (like python version wise requirements.txt) or go _out of your way_ to support Python 2, then I would suggest that you do NOT do it, and stick to Python 3.

2017-02-06 15:05 UTC, icyflame requested changes
It's a good PR, with a very good premise. The diff right now is too cluttered with these identical blocks appearing in the diff because of changed indentation, and it's hard to look at what has changed, and what has been moved forward by one space. Fixing this should be the way to go forward.

2017-02-06 15:05 UTC, icyflame commented on fbscraper.py
> +    """
This is the exact same code that's appearing in the diff because this file was apparently using 3 spaces (??) as it's previous default indent.
@ghostwriternr: In any case, this has cluttered the diff too much, and I can't really figure what are your changes, and what changes are because of this diff.
3 spaces is not a good idea, but I would suggest that you keep that PR different from this. i.e. merge this PR in and follow it up with a PR that fixes all the indentation and does NOT touch any of the code.

The problem with the current approach is that git blame will falsely accuse @ghostwriternr of writing these lines of code when he actually only shifted them forward by 1 space.

2017-02-06 15:05 UTC, icyflame commented on fbscraper.py
> +    for item in data:
Again, the indentation has caused these identical blocks to appear in the diff.

2017-02-09 14:59 UTC, ghostwriternr commented
@athityakumar @icyflame @DefCon-007 : In case you missed the notification for the updated commit 3 days back. Do let me know if it needs any more changes :smile:

2017-02-09 15:36 UTC, vivekiitkgp commented
Just to echo @icyflame's comment: Supporting Python 2 or cross compatibility is not a priority.

2017-02-09 18:47 UTC, icyflame requested changes

2017-02-09 18:47 UTC, icyflame commented on fbscraper.py
> +s = requests.Session()
This doesn't feel like a good name for a session that's being used throughout the file. Maybe you should use something like `session` or `req_session`, that way the `req_session.get` call would make more sense at first glance.

2017-02-09 18:48 UTC, icyflame commented
@ghostwriternr Patch LGTM. One pretty minor aesthetic change, the diff is a lot cleaner now, and it was easier to review.

@DefCon-007 you should ensure that this builds and updates the page properly before merging of course.

2017-02-10 09:49 UTC, ghostwriternr commented on fbscraper.py
> +s = requests.Session()
@icyflame : Aye aye sir! That's a very valid point. Updated accordingly to `req_session`.

2017-02-10 11:12 UTC, icyflame approved these changes

2017-02-11 05:43 UTC, DefCon-007 reviewed
It is working fine.

2017-02-11 05:44 UTC, DefCon-007 approved these changes

2017-02-11 05:45 UTC, merged